apiVersion: v1
data:
  spring.db.password: Z2Vvcmdl
  spring.db.username: Z2Vvcmdl
kind: Secret
metadata:
  creationTimestamp: "2023-07-31T00:47:14Z"
  name: post-secret
  namespace: spring-test
  resourceVersion: "58691"
  uid: c436632d-05fd-488c-b3b5-9b98e0117dfc
type: Opaque
